### ISSUE TITLE
App\User is extending Orchestra\Model\User not work

### ISSUE THREAD

**Issue by bahman2216** [orchestral/installer#6]
I just installed Version 3.3
All pre requirement is ok but the last one is still **red no**

Orchestra Platform strictly require Eloquent based authentication with our Role Based Access Control (RBAC) which utilize eloquent relationship. Please ensure that App\User is extending Orchestra\Model\User

**Comment by crynobone** [comment]
Yes you **HAVE** to extends `Orchestra\Model\User`.

**Comment by bahman2216** [comment]
It is already extends. But still error!

**Comment by bahman2216** [comment]
I just solved this issue by replacing driver value from `authen`  to  `eloquent` in config/auth.php
It is kidding way.

**Comment by crynobone** [comment]
Fixed under v3.3.1
